version: 1

formatters:
    simple:
        format: "%(name)s - %(lineno)d -  %(message)s"
        format: "%(message)s"

    complex:
        format: "%(asctime)s - %(name)s - %(lineno)d -  %(message)s"


handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple

    file:
        class: logging.NullHandler
        level: DEBUG
        formatter: simple

root:
  level: INFO
  handlers: [console]

loggers:

    api.expose_api_models:   
#        level: DEBUG
        handlers: [console]
        propagate: no

    logic_logger:
        level: DEBUG
        handlers: [console]
        propagate: no

    engine_logger:
#        level: DEBUG
        handlers: [console]
        propagate: no

    api_logic_server_app:
        level: INFO
        handlers: [console]
        propagate: no

    safrs:
        level: DEBUG
        handlers: [console]
        propagate: no

    sqlalchemy.engine:
#        level: DEBUG
        handlers: [console]
        propagate: no

    api.system.opt_locking:
        level: INFO
        handlers: [console]
        propagate: no

    api.customize_api:   
#        level: DEBUG
        handlers: [console]
        propagate: no

    database.customize_models:   
#        level: DEBUG
        handlers: [console]
        propagate: no

    logic.declare_logic:   
#        level: DEBUG
        handlers: [console]
        propagate: no

    security.declare_security:   
#        level: DEBUG
        handlers: [console]
        propagate: no

    integration.kafka:   
        level: DEBUG
        handlers: [console]
        propagate: no

    security.system.authentication:   
#        level: DEBUG
        handlers: [console]
        propagate: no

    security.system.authorization:   
        level: INFO
        handlers: [console]
        propagate: no

    security.authentication_provider.sql.auth_provider:   
        level: INFO
        handlers: [console]
        propagate: no

    ui.admin.admin_loader:   
#        level: DEBUG
        handlers: [console]
        propagate: no

    util:   
        level: INFO
        handlers: [console]
        propagate: no
